name: Build Android AAR

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      run: git submodule update --init
        
    - name: Prepare repository
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > $GITHUB_WORKSPACE/pkg/android/local.properties
        echo "cmake.dir=$ANDROID_SDK_ROOT/cmake/3.18.1" >> $GITHUB_WORKSPACE/pkg/android/local.properties
        export JAVA_HOME=$JAVA_HOME_11_X64
        
    - name: Build
      run: ./build.sh android-aar "release"

    - uses: actions/upload-artifact@v2
      with:
        path: dist
