name: Build Android AAR

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: adopt

    - name: Checkout submodules
      run: git submodule update --init
      
    - name: Build
      run: ./build.sh android-aar "release"

    - uses: actions/upload-artifact@v2
      with:
        path: dist
