name: Build Android AAR

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: adopt

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Checkout submodules
      run: git submodule update --init

    - name: Prepare repository
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > $GITHUB_WORKSPACE/pkg/android
      
    - name: Build
      run: ./build.sh android-aar "release"

    - uses: actions/upload-artifact@v2
      with:
        path: dist
